sudo: false
language: elixir

matrix:
  include:
    - elixir: 1.3.4
      otp_release: 18.3
    - elixir: 1.5.2
      otp_release: 20.1
    - elixir: 1.6.2
      otp_release: 21.0
    - elixir: 1.7.2
      otp_release: 21.0
